PROVIDER_DL = "ARC-ICAR"

DL_FOND_ID="448"
DL_CONSERVATORE = "san.cat.sogC.0000"
DL_HACONSERVATORE="san.cat.sogC.4980"
DL_REPOSITORYID="GGASI:IC0300014497"
DL_ABBR="GGASI:IC0300014497"
DL_CORPNAME="Archivio di Stato di Prato"
DL_HAPROGETTO ="san.cat.prjDgt.447"
DL_HACOMPLESSO ="san.cat.complArch.113436"
DL_UNITID ="DATINI:san.cat.complArch.113436"
DL_UNITTITLE ="Carteggio, Archivio di Stato di Prato, Datini, Fondaco di Avignone, Carteggio diretto al  fondaco da Aigues Mortes a Valenza"
